deployment:
  name: artistcommand
  containerPort: 6100
  replicaCount: 1
  image: 
    repository: vutiendat3601/echovibe-artistcommand
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 6100
    protocol: TCP
    hostname: api.echovibe.io.vn
    exposePathPrefix: /command/v1/artists
    replacePrefixMatch: /v1/artists
openidconnect:
  enabled: true
kafka:
  enabled: true
mongo:
  enabled: true
  uri: mongodb://echovibe_artistcommand:echovibe_artistcommand@infras.echovibe.io.vn:26100/echovibe_artistcommand?authSource=admin
datasource:
  enabled: false
  url:
  username:
  password:
