deployment:
  name: activity
  containerPort: 6300
  replicaCount: 1
  image:
    repository: vutiendat3601/echovibe-activity
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 6300
    protocol: TCP
    hostname: api.echovibe.io.vn
    exposePathPrefix: /activity/v1
    replacePrefixMatch: /v1
    upstreamSettingsPolicy:
      keepAlive:
        connections: 32
        time: "5s"
        timeout: "5s"
kafka:
  enabled: true
openidconnect:
  enabled: false
database:
  enabled: true
  vendor: "postgresql+psycopg"
  username: echovibe_activity
  password: echovibe_activity
  host: infras.echovibe.io.vn
  port: 16300
  name: echovibe_activity
redis:
  enabled: false
  url:
app:
  web:
    client:
      product:
        baseUrl: https://api.echovibe.io.vn/product
