CREATE TABLE artist (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  aggregate_id varchar(16) NOT NULL UNIQUE,
  urn varchar(255) NOT NULL UNIQUE,
  market varchar(2) NOT NULL,
  "name" varchar(255) NOT NULL,
  biography varchar(250),
  "description" text,
  is_public boolean NOT NULL DEFAULT false,
  is_published boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  thumbnail_file_key text,
  thumbnail_url text,
  background_file_key text,
  background_url text,
  tags text[] NOT NULL DEFAULT '{}',
  ref_code varchar(100) UNIQUE,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  created_by varchar(255),
  updated_by varchar(255)
);
