server:
  port: 6110
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
spring:
  application:
    name: artistquery
    version: "${BUILD_VERSION:unknown}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  docker:
    compose:
      enabled: false
  cloud:
    function:
      definition: >-
        consumeArtistCreatedEvent;
        consumeArtistUpdatedEvent;
        consumeArtistDeletedEvent;
        consumeArtistPublishedEvent;
        consumeArtistVisibilityChangedEvent;
    stream:
      bindings:
        consumeArtistCreatedEvent-in-0:
          destination: "artist.ArtistCreatedEvent"
          group: "${spring.application.name}"
        consumeArtistPublishedEvent-in-0:
          destination: "artist.ArtistPublishedEvent"
          group: "${spring.application.name}"
        consumeArtistDeletedEvent-in-0:
          destination: "artist.ArtistDeletedEvent"
          group: "${spring.application.name}"
        consumeArtistVisibilityChangedEvent-in-0:
          destination: "artist.ArtistVisibilityChangedEvent"
          group: "${spring.application.name}"
springdoc:
  api-docs:
    path: /v1/artists/openapi
  swagger-ui:
    path: /v1/artists/openapi.html
