spring:
  boot:
    admin:
      client:
        enabled: false
        url:
        - "localhost:6800"
  docker:
    compose:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - "kafka.echovibe.io.vn:9092"
