global:
  springProfilesActive: default
  kafkaBrokerUrls: http://infras.echovibe.io.vn:9092
  openIdConnectCertsUrl: https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs
  namespace: microservice