ARTIST_CREATED_EVENT = "artist.ArtistCreatedEvent"
ARTIST_RELEASED_EVENT = "artist.ArtistReleasedEvent"
ARTIST_UPDATED_EVENT = "artist.ArtistUpdatedEvent"
ARTIST_DELETED_EVENT = "artist.ArtistDeletedEvent"
ARTIST_VERIFICATION_SET_EVENT = "artist.ArtistVerificationSetEvent"
