TRACK_CREATED_EVENT = "track.TrackCreatedEvent"
TRACK_RELEASED_EVENT = "track.TrackReleasedEvent"
TRACK_UPDATED_EVENT = "track.TrackUpdatedEvent"
TRACK_DELETED_EVENT = "track.TrackDeletedEvent"
TRACK_LISTEN_MIN_SECOND = 15
TRACK_DETAIL_PAGE_VIEW_MIN_SECOND = 5
