server:
  port: 6110
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
spring:
  application:
    name: artist
  jpa:
    open-in-view: false
  docker:
    compose:
      enabled: false
  cloud:
    stream:
      bindings:
        createArtistDetails-out-0:
          destination: createArtistDetails
