TRACK_CREATED_EVENT = "track.TrackCreatedEvent"
TRACK_RELEASED_EVENT = "track.TrackReleasedEvent"
TRACK_UPDATED_EVENT = "track.TrackUpdatedEvent"
TRACK_DELETED_EVENT = "track.TrackDeletedEvent"
TRACK_AUDIO_MAPPED_EVENT = "track.TrackAudioMappedEvent"