server {
  listen 443 ssl;
  server_name admin.echovibe.io.vn;

  root /usr/share/nginx/html/echovibe-adminweb/browser;

  index index.html;

  if ($accept_language ~ "^$") {
    set $accept_language "en";
  }
  rewrite ^/$ /$accept_language permanent;
  location ~ ^/(en|vi|$) {
    try_files $uri /$1/index.html?$args;
  }
}

# server {
#   listen 443 ssl;
#   server_name echovibe.io.vn;

#   root /usr/share/nginx/html/echovibe-clientweb/browser;

#   index index.html;

#   if ($accept_language ~ "^$") {
#     set $accept_language "en";
#   }
#   rewrite ^/$ /$accept_language permanent;
#   location ~ ^/(en|vi|$) {
#     try_files $uri /$1/index.html?$args;
#   }
# }
