spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
      - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  boot:
    admin:
      client:
        enabled: false
        url:
          - "localhost:6800"
  docker:
    compose:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - "infras.echovibe.io.vn:9092"
app:
  web:
    auth:
      openIdConnectCertsUrl: https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs
    client:
      artistquery:
        baseUrl: http://localhost:6110
        enabled: true
