services:
  artist-pg:
    image: "postgres:17.2-bookworm"
    environment:
      - POSTGRES_DB=echovibe_artist
      - POSTGRES_USER=echovibe_artist
      - POSTGRES_PASSWORD=echovibe_artist
    ports:
      - "16100:5432"
  