apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.clusterIssuer.name }}-clusterissuer"
  namespace: {{ .Values.global.namespace }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.acme.email }}
    server: {{ .Values.clusterIssuer.acme.server }}
    privateKeySecretRef:
      name: "{{ .Values.clusterIssuer.name }}-cert-secret"
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: "{{ .Values.gatewayName }}-gateway"
            namespace: {{ .Values.global.namespace }}
            kind: Gateway
