name: "echovibe"
services:
  artistquery-pg-i1:
    image: "postgres:17.2-bookworm"
    environment:
      - POSTGRES_DB=echovibe_trackquery
      - POSTGRES_USER=echovibe_trackquery
      - POSTGRES_PASSWORD=echovibe_trackquery
    ports:
      - "16130:5432"
