server:
  port: 6100
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
spring:
  application:
    name: artistcommand
  docker:
    compose:
      enabled: false
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi.html
app:
  web:
    auth:
      openIdConnectCertsUrl: https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs
