name: echovibe-redis
services:
  redis-i1:
    image: "redis:7.4.3-alpine3.21"
    container_name: "echovibe-redis-i1"
    hostname: "echovibe-redis-i1"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass zhsdf23lkDLKJ3kjhfas42dkjasf863h
    volumes: 
      - ./redis/:/data/
    # mem_limit: "1g"
    restart: "on-failure:3"

networks:
  default:
    name: echovibe-redis-net
