name: echovibe-keycloak
services:
  keycloak-pg-i1:
    image: "postgres:16.6-alpine3.21"
    container_name: "echovibe-keycloak-pg-i1"
    hostname: "echovibe-keycloak-pg-i1"
    environment:
      - "POSTGRES_DB=echovibe_keycloak"
      - "POSTGRES_USER=echovibe_keycloak"
      - "POSTGRES_PASSWORD=echovibe_keycloak"
    volumes:
      - "./keycloak-pg/:/var/lib/postgresql/data"
    ports:
      - "16810:5432"
    networks:
      - "default"
  keycloak-i1:
    image: "keycloak/keycloak:26.1.2-0"
    ports:
      - "6810:6810"
    hostname: "echovibe-keycloak-i1"
    environment:
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://keycloak-pg-i1:5432/echovibe_keycloak"
      - "KC_DB_USERNAME=echovibe_keycloak"
      - "KC_DB_PASSWORD=echovibe_keycloak"
      - "KC_HOSTNAME=https://auth.echovibe.io.vn"
      - "KC_HOSTNAME_ADMIN=https://auth.echovibe.io.vn"
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=echovibe"
      - "KC_HTTP_HOST=0.0.0.0"
      - "KC_HTTP_ENABLED=true"
      - "KC_HTTP_PORT=6810"
      - "KC_HTTP_RELATIVE_PATH=/"
      - "KC_PROXY_HEADERS=xforwarded"
      - "KC_PROXY=edge"
    command: [ "start" ]
    networks:
      - "default"
  keycloak-proxy-i1:
    build:
      context: "./nginx-proxy/"
    hostname: "echovibe-keycloak-proxy-i1"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
    volumes:
      - "./nginx-proxy/log/:/app/log/"

networks:
  default:
    name: echovibe-keycloak-net
