user nginx;
worker_processes auto;

error_log /app/log/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/json;

  log_format main '[$time_iso8601]: Request="$request",IP="$remote_addr",UserAgent="$http_user_agent",Status=$status,'
                      'BodyBytesSent=$body_bytes_sent,Referrer="$http_referer",XForwardedFor="$http_x_forwarded_for"'
  access_log /app/log/access.log main;
  
  sendfile on;
  gzip on;
  keepalive_timeout 65;

  upstream echovibe-artist {
    server echovibe-artist-i1:6100;
  }

  server {
    listen 80;
    server_name api.echovibe.io.vn www.api.echovibe.io.vn;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name api.echovibe.io.vn www.api.echovibe.io.vn;

    ssl_certificate /app/tls/certificate.crt;
    ssl_certificate_key /app/tls/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
  
    location /v1/artists {
      proxy_pass http://echovibe-artist;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
