deployment:
  name: product
  containerPort: 6200
  replicaCount: 1
  image: 
    repository: vutiendat3601/echovibe-product
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 6200
    protocol: TCP
    hostname: api.echovibe.io.vn
    exposePathPrefix: /product/v1
    replacePrefixMatch: /v1
    upstreamSettingsPolicy:
      keepAlive:
        connections: 32
        time: "5s"
        timeout: "5s"
kafka:
  enabled: true
openidconnect:
  enabled: true
database:
  enabled: true
  vendor: "postgresql+psycopg"
  username: echovibe_product
  password: echovibe_product
  host: infras.echovibe.io.vn
  port: 16200
  name: echovibe_product
