name: "echovibe-pg"
services:
  echovibe-pg-i1:
    container_name: "echovibe-pg-i1"
    image: "postgres:17.2-bookworm"
    environment:
      # - POSTGRES_DB=echovibe
      # - POSTGRES_USER=echovibe
      - POSTGRES_PASSWORD=echovibe
    volumes:
      - "./initdb.d/:/docker-entrypoint-initdb.d/"
    ports:
      - "6000:5432"
