{{- define "fastapiapp-common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secret"
  namespace: {{ .Values.global.namespace }}
stringData:
    .env: |
      ENVIRONMENT={{ .Values.global.environment | default "development" }}
      KAFKA_BROKER_BOOTSTRAP_SERVER_URLS={{ .Values.global.kafkaBrokerUrls }}
      APP_WEB_AUTH_OPENIDCONNECTCERTSURL={{ .Values.global.openIdConnectCertsUrl | default "" }}
      APP_WEB_CORS_ALLOWEDORIGINPATTERNS={{ .Values.global.cors.allowedOriginPatterns | default "" }}
      APP_WEB_CORS_ALLOWEDMETHODS={{ .Values.global.cors.allowedMethods | default "" }}
      APP_WEB_CORS_ALLOWEDHEADERS={{ .Values.global.cors.allowedHeaders | default "" }}
      APP_WEB_CORS_ALLOWCREDENTIALS="{{ .Values.global.cors.allowCredentials | default "True" }}"
      APP_WEB_CORS_MAXAGE={{ .Values.global.cors.maxAge | default "" }}
      DATABASE_VENDOR={{ .Values.database.vendor | default "" }}
      DATABASE_HOST={{ .Values.database.host | default "" }}
      DATABASE_PORT={{ .Values.database.port | default "" }}
      DATABASE_USERNAME={{ .Values.database.username | default "" }}
      DATABASE_PASSWORD={{ .Values.database.password | default "" }}
      DATABASE_NAME={{ .Values.database.name | default "" }}
{{- end -}}
