{{- define "fastapiapp-common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secret"
  namespace: {{ .Values.global.namespace }}
stringData:
  DATABASE_VENDOR: {{ .Values.database.vendor | default "" }}
  DATABASE_HOST: {{ .Values.database.host | default "" }}
  DATABASE_PORT: '{{ .Values.database.port | default "" }}'
  DATABASE_USERNAME: {{ .Values.database.username | default "" }}
  DATABASE_PASSWORD: {{ .Values.database.password | default "" }}
  DATABASE_NAME: {{ .Values.database.name | default "" }}
{{- end -}}
