apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: microservice
  name: "activity-user-track-recommendation-cronjob"
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "activity-user-track-recommendation-cronjob"
              image: "curlimages/curl:8.13.0"
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - "curl --location 'http://activity-svc.microservice.svc.cluster.local/internal/v1/job/user-track-recommendation' && echo '\nProcessed activity.UserTrackRecommendation'"
          restartPolicy: OnFailure
