from enum import Enum


class ActionType(Enum):
    CREATE_PLAYLIST = "CREATE_PLAYLIST"
    UPDATE_PLAYLIST = "UPDATE_PLAYLIST"
    DELETE_PLAYLIST = "DELETE_PLAYLIST"
    LIKE_ARTIST = "LIKE_ARTIST"
    UNLIKE_ARTIST = "UNLIKE_ARTIST"
    LIKE_TRACK = "LIKE_TRACK"
    UNLIKE_TRACK = "UNLIKE_TRACK"
    VIEW_ARTIST_DETAIL_PAGE_TRACKING = "VIEW_ARTIST_DETAIL_PAGE_TRACKING"
    VIEWED_ARTIST_DETAIL_PAGE_TRACKING = "VIEWED_ARTIST_DETAIL_PAGE_TRACKING"
    VIEW_TRACK_DETAIL_PAGE_TRACKING = "VIEW_TRACK_DETAIL_PAGE_TRACKING"
    VIEWED_TRACK_DETAIL_PAGE_TRACKING = "VIEWED_TRACK_DETAIL_PAGE_TRACKING"
    LISTEN_TRACK_TRACKING = "LISTEN_TRACK_TRACKING"
    LISTENED_TRACK_TRACKING = "LISTENED_TRACK_TRACKING"
    VIEWED_SEARCH_RESULT = "VIEWED_SEARCH_RESULT"