from enum import Enum


class MessageType(Enum):
    PROCESSED_CREATE_PLAYLIST_ACTION = "PROCESSED_CREATE_PLAYLIST_ACTION"
    PROCESSED_UPDATE_PLAYLIST_ACTION = "PROCESSED_UPDATE_PLAYLIST_ACTION"
    PROCESSED_DELETE_PLAYLIST_ACTION = "PROCESSED_DELETE_PLAYLIST_ACTION"
    PROCESSED_VIEW_ARTIST_DETAIL_PAGE_ACTION = "PROCESSED_VIEW_ARTIST_DETAIL_PAGE_ACTION"
    PROCESSED_VIEW_TRACK_DETAIL_PAGE_ACTION = "PROCESSED_VIEW_TRACK_DETAIL_PAGE_ACTION"
    PROCESSED_LISTEN_TRACK_ACTION = "PROCESSED_LISTEN_TRACK_ACTION"
