from enum import Enum


class MessageType(Enum):
    PROCESSED_CREATE_PLAYLIST_ACTION = "PROCESSED_CREATE_PLAYLIST_ACTION"
    PROCESSED_UPDATE_PLAYLIST_ACTION = "PROCESSED_UPDATE_PLAYLIST_ACTION"
    PROCESSED_DELETE_PLAYLIST_ACTION = "PROCESSED_DELETE_PLAYLIST_ACTION"
    RECEIVED_VIEW_ARTIST_DETAIL_PAGE_ACTION = "RECEIVED_VIEW_ARTIST_DETAIL_PAGE_ACTION"
