export enum ActionType {
  CREATE_PLAYLIST = 'CREATE_PLAYLIST',
  UPDATE_PLAYLIST = 'UPDATE_PLAYLIST',
  DELETE_PLAYLIST = 'DELETE_PLAYLIST',
  LIKE_ARTIST = 'LIKE_ARTIST',
  UNLIKE_ARTIST = 'UNLIKE_ARTIST',
  VIEW_ARTIST_DETAIL_PAGE = 'VIEW_ARTIST_DETAIL_PAGE',
  VIEWED_ARTIST_DETAIL_PAGE = 'VIEWED_ARTIST_DETAIL_PAGE',
  LIKE_TRACK = 'LIKE_TRACK',
  UNLIKE_TRACK = 'UNLIKE_TRACK',
  VIEW_TRACK_DETAIL_PAGE = 'VIEW_TRACK_DETAIL_PAGE',
  VIEWED_TRACK_DETAIL_PAGE = 'VIEWED_TRACK_DETAIL_PAGE',
  LISTEN_TRACK = 'LISTEN_TRACK',
  LISTENED_TRACK = 'LISTENED_TRACK'
}
