export enum MessageType {
  PROCESSED_CREATE_PLAYLIST = 'PROCESSED_CREATE_PLAYLIST',
  PROCESSED_UPDATE_PLAYLIST = 'PROCESSED_UPDATE_PLAYLIST',
  PROCESSED_DELETE_PLAYLIST = 'PROCESSED_DELETE_PLAYLIST',
  PROCESSED_VIEW_ARTIST_DETAIL_PAGE_TRACKING = 'PROCESSED_VIEW_ARTIST_DETAIL_PAGE_TRACKING',
  PROCESSED_VIEW_TRACK_DETAIL_PAGE_TRACKING = 'PROCESSED_VIEW_TRACK_DETAIL_PAGE_TRACKING',
  PROCESSED_LISTEN_TRACK_TRACKING = 'PROCESSED_LISTEN_TRACK_TRACKING'
}
