name: echovibe-adminweb
services:
  proxy-i1:
    image: "nginx:stable-alpine3.20-perl"
    container_name: "echovibe-adminweb-proxy-i1"
    hostname: "echovibe-adminweb-proxy-i1"
    volumes:
      - "../../../dist/echovibe-adminweb/:/usr/share/nginx/html/echovibe-adminweb/"
      - "./conf.d/:/etc/nginx/conf.d/:ro"
    ports:
      - "80:80"
      - "443:443"
