user nginx;
worker_processes auto;

error_log /app/log/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/json;

  log_format main '[$time_iso8601]: Request="$request",IP="$remote_addr",UserAgent="$http_user_agent",Status=$status,'
                      'BodyBytesSent=$body_bytes_sent,Referrer="$http_referer",XForwardedFor="$http_x_forwarded_for"'
  access_log /app/log/access.log main;

  sendfile on;
  gzip on;
  keepalive_timeout 65;

  server {
    listen 80;
    server_name admin.echovibe.io.vn www.admin.echovibe.io.vn;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name admin.echovibe.io.vn www.admin.echovibe.io.vn;

    ssl_certificate /app/tls/admin.echovibe.io.vn/certificate.pem;
    ssl_certificate_key /app/tls/admin.echovibe.io.vn/private.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /app/echovibe-adminweb/browser;
    index index.html;

    if ($accept_language ~ "^$") {
      set $accept_language "en";
    }
    rewrite ^/$ /$accept_language permanent;

    location ~ ^/(en|vi|$) {
      try_files $uri /$1/index.html?$args;
    }
  }
}
