{{- define "springbootapp-common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secret"
  namespace: {{ .Values.global.namespace }}
stringData:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.springProfilesActive }}
  APP_WEB_AUTH_OPENIDCONNECTCERTSURL: {{ .Values.global.openIdConnectCertsUrl }}
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: {{ .Values.global.kafkaBrokerUrls }}
  SPRING_DATA_MONGODB_URI: {{ .Values.mongo.uri | default "" }}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.url | default "" }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.datasource.username | default "" }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.datasource.password | default "" }}
{{- end -}}
