apiVersion: v2
name: fastapiapp
description: Helm chart for Echo Vibe development environment
type: application
version: "1.0.0"
appVersion: "1.16.0"
dependencies:
  - name: fastapiapp-common
    version: "1.0.0"
    repository: file://../fastapiapp-common
  - name: artistquery
    version: "1.0.0"
    repository: file://../microservice/artistquery
  - name: trackquery
    version: "1.0.0"
    repository: file://../microservice/trackquery
  - name: product
    version: "1.0.0"
    repository: file://../microservice/product
