global: 
  namespace: microservice
  gatewayName: microservice
  springProfilesActive: default
  kafkaBrokerUrls: infras.echovibe.io.vn:9092
  openIdConnectCertsUrl: https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs
  cors:
    allowedOriginPatterns: "*"
    allowedMethods: "*"
    allowedHeaders: "*"
    allowCredentials: "True"
    maxAge: 60000
