name: echovibe
services:
  artist-pg-i1:
    image: "postgres:16.6-alpine3.21"
    container_name: "artist-pg-i1"
    hostname: "artist-pg-i1"
    environment:
      - "POSTGRES_DB=echovibe_artist"
      - "POSTGRES_USER=echovibe_artist"
      - "POSTGRES_PASSWORD=echovibe_artist"
    ports:
      - "16100:5432"
    networks:
      - "default"
  artist-i1:
    image: "vutiendat3601/echovibe-artist:latest"
    container_name: "echovibe-artist-i1"
    hostname: "echovibe-artist-i1"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://artist-pg-i1:5432/echovibe_artist"
      - "SPRING_DATASOURCE_USERNAME=echovibe_artist"
      - "SPRING_DATASOURCE_PASSWORD=echovibe_artist"
      - "SPRING_JPA_HIBERNATE_DDLAUTO=create-drop"
    ports:
      - "6100:6100"
    networks:
      - "default"
    depends_on:
      - "artist-pg-i1"
  apigateway-nginx-i1:
    build:
      context: "../../_infrastructure/apigateway/dev/nginx/"
    container_name: "echovibe-apigateway-nginx-i1"
    hostname: "echovibe-apigateway-nginx-i1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./log/apigateway-nginx/:/app/log/"
    networks:
      - "default"
    depends_on:
      - "artist-i1"
networks:
  default:
    name: echovibe-net
    driver: bridge
