name: echovibe
services:
  artistcommand-mongo-i1:
    image: "mongo:8.0.4"
    container_name: "echovibe-artistcommand-mongo-i1"
    hostname: "echovibe-artistcommand-mongo-i1"
    environment:
      - "MONGO_INITDB_DATABASE=echovibe_artistcommand"
      - "MONGO_INITDB_ROOT_USERNAME=echovibe_artistcommand"
      - "MONGO_INITDB_ROOT_PASSWORD=echovibe_artistcommand"
    ports:
      - "26100:27017"
    volumes:
      - "./artistcommand-mongo/:/data/db/"
    networks:
      - "default"
    restart: "on-failure:3"
  # artistcommand-i1:
  #   image: "vutiendat3601/echovibe-artistcommand:latest"
  #   container_name: "echovibe-artistcommand-i1"
  #   hostname: "echovibe-artistcommand-i1"
  #   environment:
  #     - "SPRING_DATA_MONGODB_URI=mongodb://echovibe_artistcommand:echovibe_artistcommand@echovibe-artistcommand-mongo-i1:27017/echovibe_artistcommand?authSource=admin"
  #     - "SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=infras.echovibe.io.vn:9092"
  #     - "APP_WEB_AUTH_OPENIDCONNECTCERTSURL=https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs"
  #   ports:
  #     - "6100:6100"
  #   networks:
  #     - "default"
  #   depends_on:
  #     - "artistcommand-mongo-i1"
  #   restart: "on-failure:3"
  artistquery-pg-i1:
    image: "postgres:17.2-bookworm"
    container_name: "echovibe-artistquery-pg-i1"
    hostname: "echovibe-artistquery-pg-i1"
    environment:
      - POSTGRES_DB=echovibe_artistquery
      - POSTGRES_USER=echovibe_artistquery
      - POSTGRES_PASSWORD=echovibe_artistquery
    ports:
      - "16110:5432"
    networks:
      - "default"
    volumes:
      - "./artistquery-pg/:/var/lib/postgresql/data"
    restart: "on-failure:3"
  # artistquery-i1:
  #   image: "vutiendat3601/echovibe-artistquery:latest"
  #   container_name: "echovibe-artistquery-i1"
  #   hostname: "echovibe-artistquery-i1"
  #   environment:
  #     - "KAFKA_BROKER_BOOTSTRAP_SERVER_URLS=infras.echovibe.io.vn:9092"
  #     - "DATABASE_VENDOR=postgresql+psycopg"
  #     - "DATABASE_HOST=echovibe-artistquery-pg-i1"
  #     - "DATABASE_PORT=5432"
  #     - "DATABASE_USERNAME=echovibe_artistquery"
  #     - "DATABASE_PASSWORD=echovibe_artistquery"
  #     - "DATABASE_NAME=echovibe_artistquery"
  #   ports:
  #     - "6110:6110"
  #   networks:
  #     - "default"
  #   depends_on:
  #     - "artistquery-pg-i1"
  #   restart: "on-failure:3"
  trackcommand-mongo-i1:
    image: "mongo:8.0.4"
    container_name: "echovibe-trackcommand-mongo-i1"
    hostname: "echovibe-trackcommand-mongo-i1"
    environment:
      - "MONGO_INITDB_DATABASE=echovibe_trackcommand"
      - "MONGO_INITDB_ROOT_USERNAME=echovibe_trackcommand"
      - "MONGO_INITDB_ROOT_PASSWORD=echovibe_trackcommand"
    ports:
      - "26120:27017"
    volumes:
      - "./trackcommand-mongo/:/data/db/"
    networks:
      - "default"
    restart: "on-failure:3"
    # trackcommand-i1:
    #   image: "vutiendat3601/echovibe-trackcommand:latest"
    #   container_name: "echovibe-trackcommand-i1"
    #   hostname: "echovibe-trackcommand-i1"
    #   environment:
    #     - "SPRING_DATA_MONGODB_URI=mongodb://echovibe_trackcommand:echovibe_trackcommand@echovibe-trackcommand-mongo-i1:27017/echovibe_trackcommand?authSource=admin"
    #     - "SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=infras.echovibe.io.vn:9092"
    #     - "APP_WEB_AUTH_OPENIDCONNECTCERTSURL=https://auth.echovibe.io.vn/realms/echovibe/protocol/openid-connect/certs"
    #   ports:
    #     - "6120:6120"
    #   networks:
    #     - "default"
    #   depends_on:
    #     - "trackcommand-mongo-i1"
    #   restart: "on-failure:3"
  trackquery-pg-i1:
    image: "postgres:17.2-bookworm"
    container_name: "echovibe-trackquery-pg-i1"
    hostname: "echovibe-trackquery-pg-i1"
    environment:
      - POSTGRES_DB=echovibe_trackquery
      - POSTGRES_USER=echovibe_trackquery
      - POSTGRES_PASSWORD=echovibe_trackquery
    ports:
      - "16130:5432"
    networks:
      - "default"
    volumes:
      - "./trackquery-pg/:/var/lib/postgresql/data"
    restart: "on-failure:3"
  # trackquery-i1:
  #   image: "vutiendat3601/echovibe-trackquery:latest"
  #   container_name: "echovibe-trackquery-i1"
  #   hostname: "echovibe-trackquery-i1"
  #   environment:
  #     - "KAFKA_BROKER_BOOTSTRAP_SERVER_URLS=infras.echovibe.io.vn:9092"
  #     - "DATABASE_VENDOR=postgresql+psycopg"
  #     - "DATABASE_HOST=echovibe-trackquery-pg-i1"
  #     - "DATABASE_PORT=5432"
  #     - "DATABASE_USERNAME=echovibe_trackquery"
  #     - "DATABASE_PASSWORD=echovibe_trackquery"
  #     - "DATABASE_NAME=echovibe_trackquery"
  #   ports:
  #     - "6130:6130"
  #   networks:
  #     - "default"
  #   depends_on:
  #     - "artistquery-pg-i1"
  #   restart: "on-failure:3"
  product-pg-i1:
    image: "postgres:17.2-bookworm"
    container_name: "echovibe-product-pg-i1"
    hostname: "echovibe-product-pg-i1"
    environment:
      - POSTGRES_DB=echovibe_product
      - POSTGRES_USER=echovibe_product
      - POSTGRES_PASSWORD=echovibe_product
    ports:
      - "16200:5432"
    networks:
      - "default"
    volumes:
      - "./product-pg/:/var/lib/postgresql/data"
    restart: "on-failure:3"
  # product-i1:
  #   image: "vutiendat3601/echovibe-product:latest"
  #   build:
  #     context: ../../../product/
  #   container_name: "echovibe-product-i1"
  #   hostname: "echovibe-product-i1"
  #   ports:
  #     - "6200:6200"
  #   environment:
  #     - "APP_HOST=0.0.0.0"
  #     - "APP_PORT=6200"
  #     - "DATABASE_VENDOR=postgresql+psycopg"
  #     - "DATABASE_HOST=localhost"
  #     - "DATABASE_PORT=16200"
  #     - "DATABASE_USERNAME=echovibe_product"
  #     - "DATABASE_PASSWORD=echovibe_product"
  #     - "DATABASE_NAME=echovibe_product"
  #     - "KAFKA_BROKER_BOOTSTRAP_SERVER_URLS=infras.echovibe.io.vn:9092"
  #   networks:
  #     - "default"
  #   restart: "on-failure:3"
  # apigateway-nginx-i1:
  #   build:
  #     context: "../../../_infrastructure/apigateway/local/nginx/"
  #   container_name: "echovibe-apigateway-nginx-i1"
  #   hostname: "echovibe-apigateway-nginx-i1"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./log/apigateway-nginx/:/app/log/"
  #   networks:
  #     - "default"
  #   depends_on:
  #     - "artistcommand-i1"
  #     - "artistquery-i1"
  #   restart: "on-failure:3"
  activity-pg-i1:
    image: "postgres:17.2-bookworm"
    container_name: "echovibe-activity-pg-i1"
    hostname: "echovibe-activity-pg-i1"
    environment:
      - POSTGRES_DB=echovibe_activity
      - POSTGRES_USER=echovibe_activity
      - POSTGRES_PASSWORD=echovibe_activity
    ports:
      - "16300:5432"
    networks:
      - "default"
    volumes:
      - "./activity-pg/:/var/lib/postgresql/data"
    restart: "on-failure:3"
  # activity-i1:
  #   image: "vutiendat3601/echovibe-activity:latest"
  #   build:
  #     context: ../../../activity/
  #   container_name: "echovibe-activity-i1"
  #   hostname: "echovibe-activity-i1"
  #   ports:
  #     - "6300:6300"
  #   environment:
  #     - "APP_HOST=0.0.0.0"
  #     - "APP_PORT=6300"
  #     - "DATABASE_VENDOR=postgresql+psycopg"
  #     - "DATABASE_HOST=localhost"
  #     - "DATABASE_PORT=16300"
  #     - "DATABASE_USERNAME=echovibe_activity"
  #     - "DATABASE_PASSWORD=echovibe_activity"
  #     - "DATABASE_NAME=echovibe_activity"
  #     - "KAFKA_BROKER_BOOTSTRAP_SERVER_URLS=infras.echovibe.io.vn:9092"
  #   networks:
  #     - "default"
  #   restart: "on-failure:3"
  # apigateway-nginx-i1:
  #   build:
  #     context: "../../../_infrastructure/apigateway/local/nginx/"
  #   container_name: "echovibe-apigateway-nginx-i1"
  #   hostname: "echovibe-apigateway-nginx-i1"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./log/apigateway-nginx/:/app/log/"
  #   networks:
  #     - "default"
  #   depends_on:
  #     - "artistcommand-i1"
  #     - "artistquery-i1"
  #   restart: "on-failure:3"
networks:
  default:
    name: echovibe-net
    driver: bridge
