server {
  listen 80;
  server_name admin.echovibe.io.vn;

  root /usr/share/nginx/html/echovibe-adminweb/browser/;

  index index.html;

  if ($accept_language ~ "^$") {
      set $accept_language "vi";
  }
  rewrite ^/$ /$accept_language permanent;
  location ~ ^/(en|vi|$) {
      # if ($accept_language = "") {
      #     try_files $uri /index.html?$args;
      # }
      try_files $uri /$1/index.html?$args;
  }
}
